In [5]:
import torch
import math

In [3]:
device = torch.device('mps')

In [8]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [9]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2 # every element is multiplied by 2
print(twos)

threes = ones + twos       # addition allowed because shapes are similar
print(threes)              # tensors are added element-wise
print(threes.shape)        # this has the same dimensions as input tensors

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


In [10]:
r = (torch.rand(2, 2) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.1568, -0.8619],
        [-0.5336, -0.1907]])

Absolute value of r:
tensor([[0.1568, 0.8619],
        [0.5336, 0.1907]])

Inverse sine of r:
tensor([[-0.1574, -1.0390],
        [-0.5628, -0.1919]])

Determinant of r:
tensor(-0.4300)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.9135, -0.4069],
        [-0.4069,  0.9135]]),
S=tensor([0.9370, 0.4589]),
V=tensor([[ 0.3846, -0.9231],
        [ 0.9231,  0.3846]]))

Average and standard deviation of r:
(tensor(0.3312), tensor(-0.4357))

Maximum value of r:
tensor(-0.1568)


In [11]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2162, 0.9927, 0.4128],
         [0.5938, 0.6128, 0.1519]],

        [[0.0453, 0.5035, 0.9978],
         [0.3884, 0.6929, 0.1703]]])


In [13]:
# Concatenate
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [15]:
# Triangle Lower - a triangle formation in the lower section - important as we are using these for predictions
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
# Triangle Lower - a triangle formation in the lower section - important as we are using these for predictions
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [26]:
probabilities = torch.tensor([0.1,0.2,0.3,0.4])
samples = torch.multinomial(probabilities,num_samples = 100,replacement=True)
print(samples)

tensor([2, 3, 3, 1, 0, 1, 3, 3, 1, 0, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 1, 2, 1, 2,
        1, 3, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 2, 1, 1, 2, 0, 3, 3, 2, 1, 3, 2, 0,
        3, 2, 3, 0, 3, 1, 1, 1, 3, 3, 1, 2, 3, 1, 2, 3, 3, 3, 3, 3, 2, 3, 2, 3,
        2, 1, 0, 2, 3, 3, 2, 1, 3, 1, 2, 2, 3, 1, 3, 3, 1, 3, 1, 2, 3, 3, 1, 3,
        3, 3, 3, 3])


In [32]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out
print(torch.exp(out))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [33]:
# Transposing
i = torch.zeros(2,3,4)
out = i.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [34]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([5,8,9])
tensor3 = torch.tensor([10,110,11])

out = torch.stack([tensor1,tensor2,tensor3])
print(out)

tensor([[  1,   2,   3],
        [  5,   8,   9],
        [ 10, 110,  11]])


In [36]:
import torch.nn as nn 
sample = torch.tensor([10.,10.,10.])
# Learnable
linear = nn.Linear(3,3,bias=False)
print(linear(sample))


tensor([12.0809,  4.1404,  9.9685], grad_fn=<SqueezeBackward4>)


In [38]:
import torch.nn.functional as F
tensor1 = torch.tensor([1,2,3],dtype = torch.float32)
softmax = F.softmax(tensor1,dim=0)
print(softmax)

tensor([0.0900, 0.2447, 0.6652])


In [40]:
# Using Embeddings Vectors 
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

input_indices = torch.LongTensor([1,2,3,4])

embedded_output = embedding(input_indices)
print(embedded_output.shape)

torch.Size([4, 100])


In [41]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a@b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [42]:
int_64 = torch.randint(10,(3,2))

float_32 = torch.rand(2,3)

# Uncomment the below lines to get a runtime error
# result = torch.matmul(int_64,float_32)
# print(result)